name: Categories Update

on:
  workflow_dispatch:
    inputs:
        environment:
            description: 'Environment'
            type: environment
            required: true
  #push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]
  # schedule:
  #  - cron: "* 19 * * *" # every day at 19:00 UTC

env:
    AKENEO_HOST: ${{ secrets.AKENEO_HOST }}
    AKENEO_CLIENT_ID: ${{ secrets.AKENEO_CLIENT_ID }}
    AKENEO_CLIENT_SECRET: ${{ secrets.AKENEO_CLIENT_SECRET }}
    AKENEO_USERNAME: ${{ secrets.AKENEO_USERNAME }}
    AKENEO_PASSWORD: ${{ secrets.AKENEO_PASSWORD }}
    DISCOVER_HOST: ${{ secrets.DISCOVER_HOST }}
    DISCOVER_SUBSCRIPTION_KEY: ${{ secrets.DISCOVER_SUBSCRIPTION_KEY }}

jobs:
  deploy:
    environment: ${{ inputs.environment }} 
    name: Run Update Categories ${{ inputs.environment }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create Virtual Environment
        run: |
            echo "${{ secrets.AKENEO_HOST }}" > .env
            echo "${{ secrets.AKENEO_CLIENT_ID }}" > .env
            echo "${{ secrets.AKENEO_CLIENT_SECRET }}" > .env
            echo "${{ secrets.AKENEO_USERNAME }}" > .env
            echo "${{ secrets.AKENEO_PASSWORD }}" > .env
            echo "${{ secrets.DISCOVER_HOST }}" > .env
            echo "${{ secrets.DISCOVER_SUBSCRIPTION_KEY }}" > .env
      - name: Install python-dotenv
        run: pip install python-dotenv
      - name: Install requests
        run: pip install requests
      - name: Install oauthlib
        run: pip install oauthlib
      - name: Install requests_oauthlib
        run: pip install requests_oauthlib
      - name: Install validators
        run: pip install validators
      - name: Install akeneo
        run: pip install -i https://test.pypi.org/simple/ akeneo
      - name: Run Script
        working-directory: ./src/command
        run: python setCategories.py
